config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'questions#index'

  resources :questions do
    resources :answers do
      resources :votes
    end
  end

  resources :profiles
end

app/models/answer.rb
class Answer < ApplicationRecord
  has_many :questions_answers
  has_many :votes
  has_many :questions, through: :questions_answers
  validates :content, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  has_many :questions
  has_many :votes
  validates :name, presence: true
  has_attached_file :avatar, :styles => { medium: "300x300", thumb: "100x100" }
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :questions_answers
  has_many :answers, through: :questions_answers
  belongs_to :profile
end

app/models/questions_answer.rb
class QuestionsAnswer < ApplicationRecord
  belongs_to :question
  belongs_to :answer
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_one :profile
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :answer
  belongs_to :profile
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!

  def show
    @user = User.find(current_user.id)
    if @user.profile.id == params[:id].to_i
      render :show
    else
      flash[:notice] = "You lie John Snow"
      redirect_to root_url
    end
  end

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    @profile.user = User.find(current_user)
    if @profile.save
      flash[:notice] = "Your profile has been saved!"
      redirect_to questions_path
    else
      flash[:notice] = "Your profile was not saved!"
      render :new
    end
  end

  private
    def profile_params
      params.require(:profile).permit(:name, :country, :image, :gender)
    end
end

app/controllers/questions_answers_controller.rb
class QuestionsAnswersController < ApplicationController
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, :except => [:index]
  def index
    @questions = Question.all
    @question = Question.new
  end

  # def new
  #   @question = Question.new
  # end

  def create

    @question = Question.new(profile: current_user.profile)
    @question.answers = [
        Answer.new(:content => question_params["content1"]),
        Answer.new(:content => question_params["content2"]),

    ]
    # binding.pry
    if @question.save
      @questions = Question.all
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end

    else
      @questions = Question.all
      respond_to do |format|
        flash[:notice] = "Failed to save new question"
        format.html { redirect_to root_url }
        format.js
      end
    end
  end


  private

  def question_params
    params.permit(:content1, :content2)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    @current_user = User.find(params[:current_user])
    @answer = Answer.find(params[:answer_id])
    vote = Vote.new
    vote.profile = current_user.profile
    vote.answer_id = @answer.id
    if vote.save!
      respond_to do |format|
        format.html { redirect_to root_url }
        format.js
      end
    end
  end

end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/questions_answers_helper.rb
module QuestionsAnswersHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <div class="error_messages">
    <h2>Form is invalid</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RatherClone</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="nav">
      <% if user_signed_in? %>
        <% if current_user.profile %>
          <%= link_to current_user.profile.name, profile_path(current_user.profile) %>
        <% end %>
      <%= link_to "Logout", destroy_user_session_path, method: 'delete'  %>
      <% else %>
      <%= link_to "Login", new_user_session_path  %>
      <% end %>
    </div>
    <div class="flash-msg">
      <%= flash[:alert] %>
      <%= flash[:notice] %>
    </div>


      <%= yield %>
  </body>
</html>

app/views/profiles/_form.html.erb
<%= render('layouts/errors', :object => @profile) %>

<%= form_for [@profile] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <br>
  <%= f.label :gender %>
  <%= f.text_field :gender %>
  <br>
  <%= f.label :avatar %>
  <%= f.file_field :avatar %>
  <p><%= f.submit %></p>
<% end %>

app/views/profiles/new.html.erb
<%= render 'layouts/errors', :object => @profile %>

<%= render "form"%>

app/views/profiles/show.html.erb
<h1>Profile</h1>
<h2>Name</h2>
<%= @user.profile.name %>
<p>Country</p>
<%= @user.profile.country %>
<p>Gender</p>
<%= @user.profile.gender %>
<p>Avatar</p>
<%= image_tag(current_user.profile.avatar.url(:medium))%>

app/views/questions/_form.html.erb
<div class="new-question-form">
  <%= render('layouts/errors', :object => @question) %>

  <p>Would you rather...</p>
  <%= form_tag '/questions', remote: true do %>
  <%= label_tag :content1 %>
  <%= text_field_tag :content1 %>
  <%= label_tag :content2 %>
  <%= text_field_tag :content2 %>
  <%= submit_tag %>
  <% end %>
</div>

app/views/questions/_questions.html.erb
<% @questions.each do | question |  %>
  <div class="rather-title">
    <p>Would you rather....</p>
  </div>
    <% question.answers.each do |answer| %>
    <div class="rather-choice">
      <div class="answer-display">
        <%= answer.content %>
      </div>
      <div class="answer-vote-display" id="answer-id-<%= answer.id %>">
        <%= answer.votes.count %>
      </div>
      <%= button_to "Vote", question_answer_votes_path(question, answer), remote: true, params: {:current_user => current_user}, id: "vote-id-#{answer.id}" %>
    </div>
    <% end %>
<% end %>

app/views/questions/create.js.erb
$('.questions').html('<%= j render("questions")%>')
$('.flash-msg').html('<%= flash[:notice] %>')

app/views/questions/index.html.erb
<%= render('layouts/errors', :object => @question) %>

  <div class="jumbotron">
    <h1>Would you Rather?</h1>
  </div>

<div class="container">
  <h1>Questions</h1>
  <% if current_user %>
    <%= render "form" %>
  <% end %>
  <div class="questions">
    <%= render "questions", :questions => @questions %>
  </div>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/votes/create.js.erb
$("#answer-id-<%= @answer.id %>").html("<%= @answer.votes.count %>")